### ISSUE TITLE
Create C/C++ bindings 

### ISSUE THREAD

**Issue by VMatrix1900** [ghedo/quiche#6]
Hi. I am trying to write a video streaming application. It pulls video stream from the camera and encodes it(this part is done in C++) then it will send the encoded data to transport protocol(like quiche). So I need a C++ binding for `quiche::send()`,  `quiche::connect()`, etc. How can I accomplish that?

**Comment by ghedo** [comment]
I just merged support for a C API, see [quiche.h](https://github.com/ghedo/quiche/blob/master/include/quiche.h) for some documentation as well as [client.c](https://github.com/ghedo/quiche/blob/master/examples/client.c) and [server.c](https://github.com/ghedo/quiche/blob/master/examples/server.c) for examples on how to use it.

However note that it's not quite complete yet (though it should be enough to create working clients and servers as per the examples) and as with the Rust API, the C API is not stable yet and might change in the future.
